### PR TITLE
add infinite scroll

### PR DESCRIPTION
**Pull request by bulutyerli**
Added intersection observer for detecting user scroll and created infinite scrolling based on that with Google Books api queries.

This PR addresses issue #56

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
@bulutyerli Hey, make sure to pull the latest changes from main branch to proceed further

**Comment by bulutyerli** [comment]
@suryanshsingh2001 can you check it again.

**Review by suryanshsingh2001 — APPROVED** [review]

**Comment by suryanshsingh2001** [comment]
Hey @bulutyerli , you havent taken latest changes from the last commit, Your code doesnt include the changes done in 
https://github.com/suryanshsingh2001/MyLibrary/pull/59
Please take pull from the latest changes right now. And then add your current changes.

**Comment by bulutyerli** [comment]
> Hey @bulutyerli , you havent taken latest changes from the last commit, Your code doesnt include the changes done in #59 Please take pull from the latest changes right now. And then add your current changes.

Well i did what you asked, created a new PR. I hope this time its done :)

**Pull request merged**
