### PR TITLE
Update the UI of Navbar

### PR DESCRIPTION
**Pull request by Ayusht777**

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
It seems there is problem in your code `header.jsx` 

image

**Comment by Ayusht777** [comment]
hey you have to install react-icons  pakages

**Comment by suryanshsingh2001** [comment]
> hey you have to install react-icons package

Make sure you install this dependency in your local repo so that this saved in `package.lock.json` and `package.json`, which then installed on vercel when the build command is run.

**Comment by suryanshsingh2001** [comment]
> > hey you have to install react-icons package
> 
> Make sure you install this dependency in your local repo so that this saved in `package.lock.json` and `package.json`, which then installed on vercel when the build command is run.
> 
> Simply do this. `npm i react-icons` in your `client` folder.

Then commit the changed code

**Comment by suryanshsingh2001** [comment]
Hey there,

I wanted to provide some feedback on the recent navbar implementation. Unfortunately, it doesn't quite fit with the UI of the website and appears slightly off. In comparison to the previous navbar, it doesn't seem to enhance the overall user experience.

Could you please work on designing another navbar that aligns better with the existing UI? Let's aim for a design that seamlessly integrates with the current theme and contributes positively to the user's navigation experience.

Feel free to reach out if you need any specific guidance or further information.
You can create a new PR for the improved version.
Looking forward to seeing the improved version.

**Comment by Ayusht777** [comment]
hey did you have some references for the Navbar UI

**Pull request closed without merging**
