### PR TITLE
i18n

### LINKED ISSUE #51: I18n
**Description**
I'd like to implement the i18n feature by using this library of which I'm the creator:
- npm:  [i18nPro-React](https://www.npmjs.com/package/@marchintosh94/i18n-pro-react)
- Github: [i18nPro-React](https://github.com/marchintosh94/i18nPro-react)

By using this library you'll have the flexibility to choose where store localized values (locally in the code, cdn, REST endpoint)

### PR DESCRIPTION
**Pull request by marchintosh94**
**Resolves #51:** Implemented content translation feature using [[i18nPro-react](https://github.com/marchintosh94/i18nPro-react)](https://github.com/marchintosh94/i18nPro-react)

This pull request introduces a dropdown for changing the current language and implements translation features across the application. The changes include setting up a method to get the default language, replacing texts with label tokens, and providing translations for `it` and `en-us`.

---

**Commits Overview**

- `3f4f553`: **Resolves#51 Implemented dropdown to change current language**
    
    - Added a dropdown component to allow users to switch between different languages.
    - This commit resolves issue #51.

- `11d1a0d`: **Feature: Replaced texts with label tokens and implemented translations**
    
    - Replaced static texts with label tokens that are used by the `t` method for translation.
    - Implemented translations for Italian (`it`) and US English (`en-us`).

- `75ce389`: **Feature: Created method to get default language and setup i18nPro provider**
    
    - Created a method to determine the default language when a user lands on the website.
    - Set up the `i18nPro` provider to manage internationalization.

---

**Summary**

These changes enhance the application's internationalization capabilities by introducing a language dropdown, replacing static texts with translatable tokens, and providing translations for Italian and US English. This improves the user experience by allowing users to interact with the application in their preferred language.

resolves #51

### CODE REVIEW

**Comment by marchintosh94** [comment]
Hi @suryanshsingh2001, any updates for this PR? Thanks 😁

**Comment by suryanshsingh2001** [comment]
Hey @marchintosh94 , sorry for the late response.

### 🔄 Please Fetch the Latest Changes

Hi! Before proceeding further, please make sure to **fetch the latest changes** from the main branch to ensure you're working with the most current version of the project. This helps avoid conflicts and keeps your work aligned with the team's progress.

Thank you for keeping everything in sync! 🙏

**Comment by marchintosh94** [comment]
Hi @suryanshsingh2001, I fetched last changes from the branc `main`

**Comment by suryanshsingh2001** [comment]
Hey @marchintosh94, it seems the issue persists. Your changes are still overwriting the existing ones. To avoid this, you can create a new fork, apply your changes there, and submit a pull request. This way, we can keep the current work intact without any overwriting.
I'll be closing this for now. You can create another one.

**Pull request closed without merging**
