### PR TITLE
 Feat : Added Search button

### PR DESCRIPTION
**Pull request by Arbtrage**
Added materials UI for future component styling also
image

Please review @suryanshsingh2001 .

### CODE REVIEW

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
No need to add the Search Button as the search bar is fetching books as you type a query.

**Comment by Arbtrage** [comment]
Can you provide me with some details as to how should I style the seach bar ?

**Comment by suryanshsingh2001** [comment]
> Can you provide me with some details as to how should I style the seach bar ?

Sure, You can make changes in className to style the search bar. 
Also make sure to undo any changes you did for the button.
```
 const inputProps = {
    placeholder: "Search for books",
    value,
    onChange,
    className:
      "w-full px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:border-blue-500",
  };
```

**Comment by Arbtrage** [comment]
Sure will do so.

**Pull request closed without merging**
