### PR TITLE
Improve Search Bar

### PR DESCRIPTION
**Pull request by MokshagnaV**
#34 Added react-select for Search for suggestions

### CODE REVIEW

**Review by suryanshsingh2001 — APPROVED** [review]
All things sorted. And could you please explain what does the toastId part of the code do.

**Comment by MokshagnaV** [comment]
> All things sorted. And could you please explain what does the toastId part of the code do.

Yes. I have used toastify to notify the errors. When there is any error occurs while typing in the search bar the error will be notified using toastify. But on each change in search bar multiple times the api is called so, many times the toast will display (in case of error). 

Therefore, to reduce the multiple toast notification at once. I use `toastId`. This variable will store the id of currently displaying toast and checks whenever another toast is going to call. If the `toastId` is active. If it is active, no new toast will display, else new Toast will display. 
Means a new Toast will be displayed whenever no toast is already active

**Comment by suryanshsingh2001** [comment]
> Therefore, to reduce the multiple toast notification at once. I use `toastId`. This variable will store the id of currently displaying toast and checks whenever another toast is going to call. If the `toastId` is active. If it is active, no new toast will display, else new Toast will display.

Thank you for going through all the trouble! You did a good job in improving the search bar.

**Comment by MokshagnaV** [comment]
> > Therefore, to reduce the multiple toast notification at once. I use `toastId`. This variable will store the id of currently displaying toast and checks whenever another toast is going to call. If the `toastId` is active. If it is active, no new toast will display, else new Toast will display.
> 
> Thank you for going through all the trouble! You did a good job in improving the search bar.

You're very welcome! I'm glad that my work has been helpful to you. I'm here to help for any further issues!

Thank you.

**Pull request merged**
