### PR TITLE
improve Search Bar

### PR DESCRIPTION
**Pull request by MokshagnaV**
#34  Improved Search bar
Used react-select package

### CODE REVIEW

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
PLease resolve these issues.
- [ ]  Books are not updating when clicked on suggestion bar.
- [ ]  Toastify error notifcation as soon as page loads.
- [ ]  Favicon Update not showing, , make sure to fetch the current changes made.

**Comment by MokshagnaV** [comment]
> PLease resolve these issues.
> 
>     * [ ]   Books are not updating when clicked on suggestion bar.
> 
>     * [ ]   Toastify error notifcation as soon as page loads.
> 
>     * [ ]   Favicon Update not showing, , make sure to fetch the current changes made.

Sure, Sorry for that.

**Comment by MokshagnaV** [comment]
Done
 
-  [x]   Books are not updating when clicked on suggestion bar.
 
-  [x]   Toastify error notifcation as soon as page loads.
 
-  [x]   Favicon Update not showing,

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
Please resolve this issue
- [ ] Books are still not updating when clicked on a suggestion.
- [ ] Inaccurate suggestions.

**Comment by MokshagnaV** [comment]
> Please resolve this issue
> 
>     * [ ]  Books are still not updating when clicked on a suggestion.
> 
>     * [ ]  Inaccurate suggestions.

Sorry for that.
But it's working fine for me. Can you please check it again.

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
Suggestions are working but old search are still there in the BookList. Please have a look at the demo video.

https://github.com/suryanshsingh2001/MyLibrary/assets/80690023/7a7533f3-5890-4e84-87fe-c2f5f61f0d29

**Comment by suryanshsingh2001** [comment]
@MokshagnaV Please resolve merge conflicts.

**Review by suryanshsingh2001 — APPROVED** [review]

**Comment by suryanshsingh2001** [comment]
> From the video i observed that all the searches are worked correctly. But Only for c++ the before search i.e., Hardy is remained. That means sometimes the data is not updating properly not always. Most of the time it works fine right? Even the current version of MyLibrary is also working same like that. I tried to do. But, I opened this issue is to just improve the UI of Search bar. Sorry i cannot work on it.

No problem, I tested the app and there already an issue with existing code. I'll resolve the issues and merge this PR as soon as you resolve these merge conflicts

**Pull request closed without merging**
